NAME = a.out

CC = g++

CFLAGS = -Wall -Wextra -Werror std=c++14

CLASSES = Avm.cpp

FILES = main.cpp $(CLASSES)

OBJS = $(FILES:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.cpp
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all