
NAME = a.out

CC = g++

CFLAGS =  -Wall -Wextra -Werror 

CLASSES = Avm.cpp

FILES = main.cpp $(CLASSES)

OBJS = $(FILES:.cpp=.o)

# all: $(NAME)
all:
	g++ -g -Wall -Wextra -Werror -std=c++14 *cpp

$(NAME): $(OBJS)
	$(CC)  std=c++14 $(CFLAGS) -o $@ $^

%.o: %.cpp
	$(CC) std=c++14 $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all